(cl:defpackage owd-srv
  (:use )
  (:export
   "SETGAINS"
   "<SETGAINS-REQUEST>"
   "SETGAINS-REQUEST"
   "<SETGAINS-RESPONSE>"
   "SETGAINS-RESPONSE"
   "STEPJOINT"
   "<STEPJOINT-REQUEST>"
   "STEPJOINT-REQUEST"
   "<STEPJOINT-RESPONSE>"
   "STEPJOINT-RESPONSE"
   "CALIBRATEJOINTS"
   "<CALIBRATEJOINTS-REQUEST>"
   "CALIBRATEJOINTS-REQUEST"
   "<CALIBRATEJOINTS-RESPONSE>"
   "CALIBRATEJOINTS-RESPONSE"
  ))

